### PR TITLE
I am not male.

### PR DESCRIPTION
**Pull request by MistressPlague**

### CODE REVIEW

**Comment by Katistic** [comment]
Readme no longer contains you or your name, I'm sorry I miss-gendered you.

**Comment by MistressPlague** [comment]
It is not gender. I am hermaphrodite. Also lack of creditation will lead to me taking action, you know this.

**Comment by Katistic** [comment]
I will not credit someone whose code has no place in my work, and was not referenced at any time while making the work. The credit clearly stated it was for an older version (which no longer exists, and has not for a period of time), and the work has since been rewritten in it's entirety.

**Comment by Katistic** [comment]
Please DM me on discord if you'd like to "discuss" this more.

**Pull request closed without merging**
